#include "genXml.h"
#include <stdlib.h>
#include <string.h>

FILE* open_file(const char *filename)
{
	FILE *fp = fopen(filename, "wb+");

	if (fp == NULL)
		return NULL;

	debug_output("open file : %s\n", filename);
	fprintf (fp, "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n");
	fprintf (fp, "<!-- THIS is a file generated by db_generator, Please not modify -->\n");
	fprintf (fp, "<!-- Authored by USTC 2010 SOFTWARE TEAM BIONOVO -->\n");
	return fp;
}

void close_file(FILE *fp)
{
	if (fp == NULL)
		return;
	else
		fclose(fp);
}

void put_string(FILE* fp, int tabs, const char *instring)
{
	int i;
	if (fp == NULL)
		return;

	for (i=0; i<tabs; i++)
	{
		fprintf (fp, "\t");
	}
	fprintf (fp, "%s", instring);
	return;
}

/*
 * attribute parser
 */
att_t* start_par_att()
{
	debug_output("start parser attr");
	att_t* tmp = (att_t*) malloc(sizeof(att_t));
	if (tmp != NULL)
	{
		tmp->next = NULL;
		tmp->name = NULL;
		tmp->value = NULL;
		tmp->size = 0;
	}
	return tmp;
}

void add_att(att_t* head, const char* name, const char* value)
{
	att_t* tmp = (att_t*) malloc(sizeof(att_t));
	if ((name == NULL) 
			|| (value == NULL))
		return;

	int namelen = strlen(name);
	int valuelen = strlen(value);
	if (valuelen == 0)
		return;

	att_t* list_end = head;
	while(list_end->next != NULL)
		list_end = list_end->next;

	if (tmp != NULL)
	{
		tmp->next = NULL;
		tmp->name = (char*)strdup(name);
		tmp->value = (char*)strdup(value);
		if ((tmp->name == NULL) 
				|| (tmp->value == NULL))
		{
			free(tmp);
			return;
		}
		tmp->size = namelen + valuelen + 1;
		head->size += tmp->size;
	}

	list_end->next = tmp;
	debug_output("add attr: %s %s\n", name, value);
	return;
}

char* make_node_str(const char *node_name, att_t* head, const char* value)
{
	debug_output("make_node_name_str: %s \n", node_name);
	char* start = "<";
	char* end_1 = "/>";
	char* end_2 = ">";
	int value_len = 0;
	int attr_size = 0;

	if ((head == NULL)
			|| (node_name == NULL))
		return NULL;

	if (value != NULL)
		value_len = strlen(value);

	att_t *itr = head;
	while (1)
	{
		itr = itr->next;
		if (itr != NULL)
		{
			attr_size += 1; //加上空格
			attr_size += 2; //加上引号
		}
		else 
			break;

		attr_size += itr->size;
	}
	if ((attr_size == 0) && (value_len == 0))
		return NULL;

	int size = 2*strlen(node_name) + 1;
	size += 2*strlen(start); //strlen("<"); <字符
	size += 2*strlen(end_1); //strlen(">") >字符
	size += value_len;
	size += attr_size;
	size += 1; /* \0 */

	char *strbuf = (char *) malloc(size * sizeof(char));
	memset(strbuf, 0, size*sizeof(char));
	if (strbuf == NULL)
		return NULL;

	int npos = 0;
	npos += sprintf(strbuf+npos, "%s%s", start, node_name);
	itr = head;
	while (1)
	{
		itr = itr->next;
		if (itr != NULL)
		{
			npos += sprintf(strbuf+npos, " ");
		}
		else 
			break;

		npos += sprintf(strbuf+npos, "%s=\"%s\"", itr->name, itr->value);
	}

	if (value_len == 0)
	{
		npos += sprintf(strbuf+npos, "%s", end_1);
	}
	else
	{
		npos += sprintf(strbuf+npos, "%s%s</%s>", end_2, value, node_name);
	}
	return strbuf;
}

char* make_node_name_str(const char *node_name, att_t* head)
{
	debug_output("make_node_name_str: %s \n", node_name);
	char* start = "<";
	char* end= ">";

	if ((head == NULL)
			|| (node_name == NULL))
		return NULL;

	int size = strlen(node_name) + 1;
	size += strlen(start); //strlen("<"); <字符
	size += strlen(end); //strlen(">") >字符

	att_t *itr = head;
	while (1)
	{
		itr = itr->next;
		if (itr != NULL)
		{
			size += 1; //加上空格
			size += 2; //加上双引号
		}
		else 
			break;

		size += itr->size;
	}

	size += 1; /* \0 */
	char *strbuf = (char *) malloc(size * sizeof(char));
	memset(strbuf, 0, size*sizeof(char));
	if (strbuf == NULL)
		return NULL;

	int npos = 0;
	npos += sprintf(strbuf+npos, "%s%s", start, node_name);
	itr = head;
	while (1)
	{
		itr = itr->next;
		if (itr != NULL)
		{
			npos += sprintf(strbuf+npos, " ");
		}
		else 
			break;

		npos += sprintf(strbuf+npos, "%s=\"%s\"", itr->name, itr->value);
	}
	npos += sprintf(strbuf+npos, "%s", end);

	return strbuf;
}

void end_par_att(att_t *head)
{
	if (head == NULL)
		return;

	att_t *tmp = head;
	att_t *tmphead = tmp->next;
	while (tmphead != NULL)
	{
		free(tmp);
		tmp = tmphead;
		tmphead = tmphead->next;
	}
	free(tmp);
}

void finish_make_node_name_str(char *str, att_t **head)
{
	if (head == NULL)
		return;

	end_par_att(*head);
	*head = NULL;

	if (str != NULL)
	{
		free(str);
	}
}

void init_stack(stack *s)
{
	if (s == NULL)
		return;

	s->top = 0;
}

void push_stack(stack *s, int value)
{
	debug_output("stack: push %d\n", value);
	if (s == NULL)
		return;
	s->values[s->top] = value;
	s->top += 1;
}

void pop_stack(stack *s)
{
	debug_output("stack: pop %d\n", s->values[s->top-1]);
	if (s == NULL)
		return;
	s->top -= 1;
	if (s->top < 0)
		s->top = 0;
}

int top_stack(stack *s)
{
	debug_output("stack: top %d\n", s->values[s->top-1]);
	if (s == NULL)
		return -1;

	return s->values[s->top-1];
}

bool isempty(stack *s)
{
	if (s == NULL)
		return true;
	
	debug_output("stack: empty %d\n", s->top==0);
	return s->top == 0 ? true : false;
};
