file = [amp_tm_pSB1A3.xml]

MoDeL
{
	reaction id = [amp_tm_pSB1A3], name = [amplification of tm_pSB1A3], reversible = [false], fast = [false]
	{
		interface
		{
			url:[http://2010.igem.org/Team:USTC_Software];
			short_desc:[amplification of plasmid template pSB1A3];
		}
		listOfCompartments
		{
			compartment
			{
				compartmentReference:[Flask];
				currentCompartmentLabel:[Flask];
				parentCompartmentLabel:[ROOT];
			}
			compartment
			{
				compartmentReference:[E_coli];
				currentCompartmentLabel:[E_coli];
				parentCompartmentLabel:[Flask];
			}
		}
		listOfReactants
		{
		}
		listOfModifiers
		{
			modifier
			{
				speciesReference:[tm_pSB1A3];
				speciesLabel:[tm_pSB1A3_0];
				compartmentLabel:[E_coli] itself = [];
			}
		}
		listOfProducts
		{
			product
			{
				speciesReference:[tm_pSB1A3];
				speciesLabel:[tm_pSB1A3_1];
				compartmentLabel:[E_coli] itself = [];
			}
		}
		listOfSubstituentTransfers
		{
		}
		kineticLaw
		{
			forwardKineticlaw
			{
				math:[kgrowth*tm_pSB1A3_0*E_coli];
				listOfLocalParameters
				{
					localParameter
					{
						id:[kgrowth];
						name:[rate of growth];
						value:[1.0];
						units:[per_second];
						constant:[true];
					}
				}
				listOfReferencedParameters
				{
				}
				listOfConstraints
				{
				}
			}
			reverseKineticLaw
			{
			}
		}
	}
}
