file = [kill_Ecoli_by_ampicillin.xml]

MoDeL
{
	reaction id = [kill_Ecoli_by_ampicillin], name = [kill_Ecoli_by_ampicillin], reversible = [false], fast = [false]
	{
		interface
		{
			url:[http://2010.igem.org/Team:USTC_Software];
			short_desc:[kill_Ecoli_by_ampicillin];
		}
		listOfCompartments
		{
			compartment
			{
				compartmentReference:[Flask];
				currentCompartmentLabel:[Flask];
				parentCompartmentLabel:[ROOT];
			}
			compartment
			{
				compartmentReference:[E_coli];
				currentCompartmentLabel:[E_coli];
				parentCompartmentLabel:[Flask];
			}
		}
		listOfReactants
		{
			reactant	
			{
				speciesReference:[E_coli_cell];
				speciesLabel:[E_coli_cell];
				compartmentLabel:[Flask] itself = [E_coli];
			}
		}
		listOfModifiers
		{
			modifier
			{
				speciesReference:[ampicillin_compound];
				speciesLabel:[ampicillin_compound];
				compartmentLabel:[E_coli] itself = [];
			}
		}
		listOfProducts
		{
		}
		listOfSubstituentTransfers
		{
		}
		kineticLaw
		{
			forwardKineticlaw
			{
				math:[kdeath*(E_coli_cell*Flask)*(ampicillin_compound*E_coli)];
				listOfLocalParameters
				{
					localParameter
					{
						id:[kdeath];
						name:[E_coli death rate with ampicillin_compound];
						value:[1E-4];
						units:[per_mole_per_second];
						constant:[true];
					}
				}
				listOfReferencedParameters
				{
				}
				listOfConstraints
				{
				}
			}
			reverseKineticLaw
			{
			}
		}
	}
}
