#!/bin/sh

# set path
export QTDIR="C:\\Qt\\2010.05\\qt"
export PATH="$PATH;C:\\Qt\\2010.05\\qt\\bin"
export PATH="$PATH;C:\\Qt\\2010.05\\bin;C:\\Qt\\2010.05\\mingw\\bin"
export QMAKESPEC="win32-g++"

# qmake a Makefile
/c/Qt/2010.05/qt/bin/qmake iGaME.pro

# here fixed a bug in Makefile generated by qmake for Windows
mv Makefile Makefile.temp
sed 's/binidc.exe/bin\/idc.exe/g; s/binuic.exe/bin\/uic.exe/g; s/binmoc.exe/bin\/moc.exe/g;' Makefile.temp >Makefile
rm Makefile.temp

# make in MinGW
/c/Qt/2010.05/mingw/bin/mingw32-make
